name: '[Entire] Build Release Version'

on:
  release:
    tags:
      - 'v*'

permissions:
  contents: write
  discussions: write
  id-token: write

env:
  CARGO_INCREMENTAL: 0
  RUST_BACKTRACE: short

jobs:
  windows_x86_64_build:
    name: Windows x86_64 Build
    uses: ./.github/workflows/deps-build-windows-nsis.yaml
    with:
      portable: true
      fixed-webview: false
      nightly: false
      arch: 'x86_64'
      tag: ${{ github.event.release.tag_name }}
    secrets: inherit

  windows_aarch64_build:
    name: Windows aarch64 Build
    uses: ./.github/workflows/deps-build-windows-nsis.yaml
    with:
      portable: true
      fixed-webview: false
      nightly: false
      arch: 'aarch64'
      tag: ${{ github.event.release.tag_name }}
    secrets: inherit

  upload_release_assets:
    name: Upload Release Assets
    needs: [windows_x86_64_build, windows_aarch64_build]
    uses: ./.github/workflows/deps-upload-release-assets.yaml
    with:
      tag: ${{ github.event.release.tag_name }}

  updater:
    name: Create Updater
    needs: [upload_release_assets]
    uses: ./.github/workflows/deps-create-updater.yaml
    with:
      nightly: false
    secrets: inherit
